---
title       : Explore 1974 Motor Trend dataset
subtitle    : with shiny app
author      : Dmitry Kolodezev
job         : student
framework   : html5slides   # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
## Explore 1974 Motor Trend dataset
```{r echo=FALSE}
data(mtcars)
fit <- lm(mpg~am+cyl+am:cyl, mtcars)
res <- residuals(fit)
fits <- fitted(fit)
```

If you goal 

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

---------------------
## Scatterplot
slide2

```{r}

```
---------------------
## Regression coefficients
```
Model: lm(mpg~am+cyl+am:cyl)
```

```{r echo=FALSE}
summary(fit)$coeff
```

---------------------
## QQ Plot
```
Model: lm(mpg~am+cyl+am:cyl)
```

```{r echo=FALSE}
parmar <- par('mar')
par(mar = c(4, 4, 0, 2))
qqnorm(res, main='')
qqline(res, main='')
par(mar=parmar)
```

---------------------
## Resuduals Plot
```
Model: lm(mpg~am+cyl+am:cyl)
```

```{r echo=FALSE}
parmar <- par('mar')
par(mar = c(4, 4, 0, 2))
plot(res ~ fits)
abline(h = 0)
par(mar=parmar)

```

